### ISSUE TITLE
Enable DeepSee should get an actual csp app

### ISSUE THREAD

**Issue by eduard93** [evshvarov/isc-one-liners#1]
https://github.com/evshvarov/isc-one-liners/blob/618d1b21ac79b41c0171d7bd084e1b1bc8d76f69/src/iris/dc/one/Line.cls#L34

**Comment by evshvarov** [comment]
It’s a one-liner. So the idea is that you copy and use it in your
code/terminal with your app

Вс, 13 февр. 2022 г. в 11:37, Eduard ***@***.***>:

**Comment by evshvarov** [comment]
But maybe we could change it to take a current namespace and lowercase it

Вс, 13 февр. 2022 г. в 12:55, Евгений Шваров ***@***.***>:
