### ISSUE TITLE
Badge license leads to 404 error in readme.md

### ISSUE THREAD

**Issue by SergeyMi37** [evshvarov/isc-one-liners#2]
![image](https://user-images.githubusercontent.com/18187317/153769795-2359ca19-5998-4b3e-952b-26fcbdc8fb4a.png)

**Comment by SergeyMi37** [comment]
And the other badge also leads the wrong way
![image](https://user-images.githubusercontent.com/18187317/153770027-c704273e-839c-442a-b751-8acc5a690126.png)

**Comment by evshvarov** [comment]
fixed
